'use strict';

/**
 * markdown-codec.js — Serialize/deserialize observations as markdown files
 * with YAML frontmatter. Used by the Git-sync module to convert between
 * SQLite observations and .cortex/global/*.md files in the team memory repo.
 *
 * Format:
 *   ---
 *   id: 1423
 *   type: error
 *   title: "Using raw fetch() in tests causes port conflicts"
 *   confidence: 90
 *   ...
 *   ---
 *   Content body here...
 *
 *   ## Relations
 *   - derives_from → 1204 (Port conflict investigation)
 *
 * @module sync/markdown-codec
 */

/**
 * Encode an observation + its relations into a markdown string.
 * @param {Object} obs - Observation row from SQLite
 * @param {Array<Object>} [relations] - Relations where obs is source
 * @returns {string} Markdown with YAML frontmatter
 */
function encodeObservation(obs, relations) {
  let md = '---\n';
  md += 'id: ' + obs.id + '\n';
  md += 'type: ' + (obs.type || 'observation') + '\n';
  if (obs.title) md += 'title: "' + _escapeYaml(obs.title) + '"\n';
  md += 'confidence: ' + (obs.confidence ?? 100) + '\n';
  md += 'importance: ' + (obs.importance ?? 5) + '\n';
  md += 'provenance: ' + (obs.provenance || 'observed') + '\n';
  if (obs.agent_id) md += 'agent_id: "' + _escapeYaml(obs.agent_id) + '"\n';
  if (obs.session_id) md += 'session_id: "' + _escapeYaml(obs.session_id) + '"\n';
  if (obs.created_at) md += 'created_at: "' + obs.created_at + '"\n';

  // Tags
  let tags = [];
  try { tags = typeof obs.tags === 'string' ? JSON.parse(obs.tags) : (obs.tags || []); } catch { tags = []; }
  if (tags.length > 0) {
    md += 'tags: [' + tags.map(t => '"' + _escapeYaml(t) + '"').join(', ') + ']\n';
  }

  // Skill/procedure fields
  if (obs.steps) {
    let steps;
    try { steps = typeof obs.steps === 'string' ? JSON.parse(obs.steps) : obs.steps; } catch { steps = null; }
    if (steps) md += 'steps: ' + JSON.stringify(steps) + '\n';
  }
  if (obs.triggers) {
    let triggers;
    try { triggers = typeof obs.triggers === 'string' ? JSON.parse(obs.triggers) : obs.triggers; } catch { triggers = null; }
    if (triggers) md += 'triggers: ' + JSON.stringify(triggers) + '\n';
  }

  // Sync metadata
  md += 'synced_at: "' + new Date().toISOString() + '"\n';
  md += '---\n\n';

  // Content body
  md += (obs.content || '') + '\n';

  // Relations footer
  if (relations && relations.length > 0) {
    md += '\n## Relations\n';
    md += '<!-- AUTO-GENERATED by agentic-cortex -->\n';
    for (const rel of relations) {
      md += '- ' + rel.relation_type + ' → ' + rel.target_id + (rel.target_title ? ' (' + rel.target_title + ')' : '') + '\n';
    }
  }

  return md;
}

/**
 * Decode a markdown string into an observation object + relations array.
 * @param {string} mdString - Full markdown content
 * @returns {{ observation: Object, relations: Array<{target_id: number, relation_type: string}> }}
 */
function decodeMarkdown(mdString) {
  const frontmatterEnd = mdString.indexOf('\n---\n');
  if (frontmatterEnd === -1) {
    throw new Error('Invalid markdown: no YAML frontmatter found');
  }

  const fmText = mdString.slice(4, frontmatterEnd); // skip leading '---\n'
  const bodyStart = frontmatterEnd + 5; // skip '\n---\n'

  const fm = _parseFrontmatter(fmText);

  // Split body from relations
  const relationsIndex = mdString.indexOf('\n## Relations\n');
  let content, relations = [];

  if (relationsIndex !== -1) {
    content = mdString.slice(bodyStart, relationsIndex).trim();
    relations = _parseRelations(mdString.slice(relationsIndex));
  } else {
    content = mdString.slice(bodyStart).trim();
  }

  const observation = {
    id: fm.id ? parseInt(fm.id, 10) : null,
    type: fm.type || 'observation',
    title: fm.title || null,
    content: content,
    confidence: fm.confidence != null ? parseInt(fm.confidence, 10) : 100,
    importance: fm.importance != null ? parseInt(fm.importance, 10) : 5,
    provenance: fm.provenance || 'observed',
    agent_id: fm.agent_id || null,
    session_id: fm.session_id || null,
    tags: fm.tags || [],
    created_at: fm.created_at || null,
    steps: fm.steps || null,
    triggers: fm.triggers || null,
    preconditions: fm.preconditions || null,
    postconditions: fm.postconditions || null,
    synced_at: fm.synced_at || null,
  };

  return { observation, relations };
}

/**
 * Parse YAML frontmatter text into a key-value object.
 * Handles strings, integers, arrays, and quoted strings.
 * @param {string} fmText
 * @returns {Object}
 */
function _parseFrontmatter(fmText) {
  const result = {};
  const lines = fmText.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const colonIdx = line.indexOf(':');
    if (colonIdx === -1) continue;

    const key = line.slice(0, colonIdx).trim();
    let value = line.slice(colonIdx + 1).trim();

    // Handle arrays: tags: [tag1, tag2]
    if (value.startsWith('[') && value.endsWith(']')) {
      try {
        result[key] = JSON.parse(value);
      } catch {
        result[key] = value.slice(1, -1).split(',').map(s => s.trim().replace(/^"|"$/g, ''));
      }
      continue;
    }

    // Handle JSON arrays/objects for steps, triggers, etc.
    if ((value.startsWith('[') || value.startsWith('{')) && !value.endsWith(']') && !value.endsWith('}')) {
      // Multi-line JSON — collect until balanced
      const fullValue = _collectJson(lines, i, value);
      try {
        result[key] = JSON.parse(fullValue);
      } catch {
        result[key] = fullValue;
      }
      continue;
    }

    // Remove surrounding quotes
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Try parse as number
    if (/^-?\d+$/.test(value)) {
      result[key] = parseInt(value, 10);
    } else if (/^-?\d+\.\d+$/.test(value)) {
      result[key] = parseFloat(value);
    } else {
      result[key] = value;
    }
  }

  return result;
}

/**
 * Collect a multi-line JSON value from YAML frontmatter.
 */
function _collectJson(lines, startIdx, startValue) {
  let json = startValue;
  let depth = (startValue.match(/\[/g) || []).length - (startValue.match(/\]/g) || []).length;
  depth += (startValue.match(/\{/g) || []).length - (startValue.match(/\}/g) || []).length;

  for (let i = startIdx + 1; i < lines.length && depth > 0; i++) {
    const line = lines[i].trim();
    json += line;
    depth += (line.match(/\[/g) || []).length - (line.match(/\]/g) || []).length;
    depth += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
  }
  return json;
}

/**
 * Parse the relations footer.
 * Format: "- derives_from → 1204 (Port conflict investigation)"
 * @param {string} relationsText
 * @returns {Array<{target_id: number, relation_type: string}>}
 */
function _parseRelations(relationsText) {
  const relations = [];
  const lines = relationsText.split('\n');
  for (const line of lines) {
    // Match: "- relation_type → target_id" with optional "(title)"
    const match = line.match(/^-\s*(\S+)\s*→\s*(\d+)/);
    if (match) {
      relations.push({
        relation_type: match[1],
        target_id: parseInt(match[2], 10),
      });
    }
  }
  return relations;
}

/**
 * Escape a string for safe YAML double-quoted inclusion.
 * @param {string} str
 * @returns {string}
 */
function _escapeYaml(str) {
  if (!str) return '';
  return String(str)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

/**
 * Generate a filesystem-safe filename for an observation.
 * Format: {type}__{id}__{slug}.md
 * @param {Object} obs
 * @returns {string}
 */
function generateFilename(obs) {
  const type = (obs.type || 'observation').replace(/[^a-z0-9-]/g, '-');
  const id = String(obs.id).padStart(4, '0');
  const title = (obs.title || 'untitled')
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
    .slice(0, 50);
  const slug = title || 'obs-' + id;
  return type + '__' + id + '__' + slug + '.md';
}

module.exports = { encodeObservation, decodeMarkdown, generateFilename };
