'use strict';

const { describe, it, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const os = require('os');
const fs = require('fs');
const Database = require('better-sqlite3');
const { ensureSchema } = require('../src/core/db');
const codeIndex = require('../src/core/code-index');
const compactor = require('../src/core/compactor');

// Memory safety: NEVER load the real ~400MB embedding model in tests.
// Stub it deterministically and leave embeddings disabled.
const embedding = require('../src/core/embedding');
embedding.computeEmbedding = async function (text) {
  return Array.from({ length: 16 }, (_, i) => ((text || '').length + i) % 7);
};
process.env.AGENTIC_CORTEX_EMBEDDINGS = process.env.AGENTIC_CORTEX_EMBEDDINGS || '0';

/** Create a fresh in-memory DB with the full schema. */
function createTestDb() {
  const db = new Database(':memory:');
  db.pragma('journal_mode = WAL');
  db.pragma('foreign_keys = ON');
  ensureSchema(db);
  return db;
}

/** Build a small synthetic graph (as generated by scripts/generate-graph.mjs). */
function buildGraph() {
  const node = (symbols, extra = {}) => ({
    path: extra.path || 'src/file.js',
    role: 'library',
    exports: symbols.map(s => s.name),
    imports: extra.imports || [],
    symbols,
    ...extra,
  });
  return {
    fingerprint: 'test',
    fileCount: 3,
    apiRoutes: [],
    services: {},
    prismaSchema: { models: [], enums: [] },
    layerMap: { layerCounts: { UI: 0, API: 0, Service: 3, Data: 0 }, crossLayerEdges: {}, requestPath: '', hubFiles: [] },
    paradigms: [],
    techStack: { runtime: ['JavaScript'], frameworks: [], databases: [], tools: [] },
    graph: {
      'src/core/embedding.js': node([
        { name: 'computeEmbedding', kind: 'function', signature: 'async function computeEmbedding(text)', doc: 'Compute a vector embedding for text', body: '{\n  return vec;\n}', startLine: 10 },
        { name: 'cosineSimilarity', kind: 'function', signature: 'function cosineSimilarity(a, b)', doc: 'Cosine similarity between two vectors', body: '{\n  return dot / norm;\n}', startLine: 30 },
      ], { imports: [], exports: ['computeEmbedding', 'cosineSimilarity'] }),
      'src/core/search.js': node([
        { name: 'hybridSearch', kind: 'function', signature: 'function hybridSearch(db, query, vec)', doc: 'Hybrid keyword + semantic search', body: '{\n  return results;\n}', startLine: 5 },
      ], { imports: ['./embedding'], exports: ['hybridSearch'] }),
      'src/core/session.js': node([
        { name: 'startSession', kind: 'function', signature: 'function startSession(db, opts)', doc: 'Start a new memory session', body: '{\n  return sid;\n}', startLine: 5 },
      ], { imports: [], exports: ['startSession'] }),
    },
  };
}

// ─── Schema ─────────────────────────────────────────────────────────

describe('code-index schema', () => {
  let db;
  beforeEach(() => { db = createTestDb(); });
  afterEach(() => { db.close(); });

  it('creates code_symbols, code_symbols_fts, and session_compactions tables', () => {
    for (const t of ['code_symbols', 'code_symbols_fts', 'session_compactions']) {
      const row = db.prepare("SELECT name FROM sqlite_master WHERE type IN ('table','virtual') AND name = ?").get(t);
      assert.ok(row, t + ' should exist');
    }
  });

  it('creates the code_symbols unique constraint', () => {
    const idx = db.prepare("SELECT * FROM sqlite_master WHERE type = 'table' AND name = 'code_symbols'").get();
    assert.ok(idx.sql.includes('UNIQUE(project_path, file_path, symbol_name, kind)'));
  });
});

// ─── Ingestion ──────────────────────────────────────────────────────

describe('code-index ingestion', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-codeidx-test-' + Date.now());
  beforeEach(() => { db = createTestDb(); });
  afterEach(() => { db.close(); });

  it('ingests symbols from a graph object', () => {
    const r = codeIndex.ingestProject(db, project, { graph: buildGraph() });
    assert.equal(r.status, 'ok');
    assert.equal(r.symbols, 4);
    assert.equal(r.inserted, 4);
    const rows = db.prepare('SELECT * FROM code_symbols WHERE project_path = ?').all(project);
    assert.equal(rows.length, 4);
    const emb = rows.find(x => x.symbol_name === 'computeEmbedding');
    assert.equal(emb.file_path, 'src/core/embedding.js');
    assert.equal(emb.body, '{\n  return vec;\n}');
    assert.equal(emb.body_hash.length, 16);
  });

  it('is idempotent — re-ingest with unchanged bodies updates nothing', () => {
    codeIndex.ingestProject(db, project, { graph: buildGraph() });
    const r2 = codeIndex.ingestProject(db, project, { graph: buildGraph() });
    assert.equal(r2.inserted, 0);
    assert.equal(r2.updated, 0);
  });

  it('updates symbols when a body changes and preserves summaries', () => {
    codeIndex.ingestProject(db, project, { graph: buildGraph() });
    db.prepare('UPDATE code_symbols SET summary = ? WHERE symbol_name = ?').run('summarizes text', 'computeEmbedding');
    const g2 = buildGraph();
    g2.graph['src/core/embedding.js'].symbols[0].body = '{\n  return newVec;\n}';
    const r = codeIndex.ingestProject(db, project, { graph: g2 });
    assert.equal(r.updated, 1);
    const row = db.prepare("SELECT * FROM code_symbols WHERE symbol_name = 'computeEmbedding'").get();
    assert.equal(row.summary, 'summarizes text', 'existing summary must survive re-ingest');
    assert.equal(row.body, '{\n  return newVec;\n}');
  });

  it('drops symbols for files removed from the graph on full ingest', () => {
    codeIndex.ingestProject(db, project, { graph: buildGraph() });
    const g2 = buildGraph();
    delete g2.graph['src/core/session.js'];
    codeIndex.ingestProject(db, project, { graph: g2 });
    const count = db.prepare("SELECT COUNT(*) c FROM code_symbols WHERE symbol_name = 'startSession'").get().c;
    assert.equal(count, 0);
  });
});

// ─── Search ─────────────────────────────────────────────────────────

describe('code-index search', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-codeidx-search-' + Date.now());
  beforeEach(() => { db = createTestDb(); codeIndex.ingestProject(db, project, { graph: buildGraph() }); });
  afterEach(() => { db.close(); });

  it('finds symbols by keyword (FTS5)', () => {
    const results = codeIndex.keywordSymbolSearch(db, 'cosine', { project });
    assert.ok(results.length >= 1);
    assert.equal(results[0].symbol_name, 'cosineSimilarity');
  });

  it('finds symbols by doc content', () => {
    const results = codeIndex.keywordSymbolSearch(db, 'session', { project });
    assert.ok(results.some(r => r.symbol_name === 'startSession'));
  });

  it('hybrid search falls back to keyword when embeddings unavailable', async () => {
    const results = await codeIndex.searchSymbols(db, 'hybrid', { project });
    assert.ok(results.length >= 1);
  });

  it('does not attempt embeddings when disabled (no model load)', async () => {
    let called = 0;
    const orig = embedding.computeEmbedding;
    embedding.computeEmbedding = async () => { called++; return [1, 2, 3]; };
    try {
      await codeIndex.searchSymbols(db, 'hybrid', { project, semantic: true });
    } finally {
      embedding.computeEmbedding = orig;
    }
    assert.equal(called, 0, 'embeddings must stay disabled by default — keyword only');
  });

  it('records access for returned symbols', async () => {
    await codeIndex.searchSymbols(db, 'hybrid', { project });
    await codeIndex.searchSymbols(db, 'hybrid', { project });
    const row = db.prepare("SELECT access_count, last_accessed_at FROM code_symbols WHERE symbol_name = 'hybridSearch'").get();
    assert.ok(row.access_count >= 1, 'retrieval must bump access_count');
    assert.ok(row.last_accessed_at, 'last_accessed_at must be set');
  });
});

// ─── Task-scoped retrieval ─────────────────────────────────────────

describe('code-index task-scoped retrieval', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-codeidx-scoped-' + Date.now());
  beforeEach(() => { db = createTestDb(); codeIndex.ingestProject(db, project, { graph: buildGraph() }); });
  afterEach(() => { db.close(); });

  it('returns symbols from task-relevant files with bodies', () => {
    const { symbols, stats } = codeIndex.getTaskScopedSymbols(db, project, 'vector embedding similarity', 2000, { graph: buildGraph() });
    assert.ok(symbols.length >= 1);
    assert.ok(symbols.some(s => s.symbol_name === 'computeEmbedding'));
    assert.ok(symbols.some(s => s.symbol_name === 'cosineSimilarity'));
    assert.ok(symbols.every(s => s.file_path !== 'src/core/session.js'), 'irrelevant file should not dominate');
    assert.ok(stats.estimatedTokens <= 500);
  });

  it('expands into the import closure (search.js imports embedding.js)', () => {
    const { files } = codeIndex.getTaskScopedSymbols(db, project, 'hybrid search', 4000, { graph: buildGraph() });
    assert.ok(files.includes('src/core/search.js'));
    assert.ok(files.includes('src/core/embedding.js'));
  });

  it('caps symbols per file so the budget spreads across files', () => {
    const { symbols } = codeIndex.getTaskScopedSymbols(db, project, 'embedding search session', 4000, { symbolsPerFile: 1, graph: buildGraph() });
    const files = new Set(symbols.map(s => s.file_path));
    assert.ok(files.size >= 2);
  });

  it('respects a tiny token budget', () => {
    const { symbols, stats } = codeIndex.getTaskScopedSymbols(db, project, 'embedding', 200, { graph: buildGraph() });
    assert.ok(stats.estimatedTokens <= 250, 'should stay near budget');
    assert.ok(symbols.length >= 1);
  });
});

// ─── Access tracking + usage-weighted injection ─────────────────────

describe('code-index access tracking', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-codeidx-access-' + Date.now());
  beforeEach(() => { db = createTestDb(); codeIndex.ingestProject(db, project, { graph: buildGraph() }); });
  afterEach(() => { db.close(); });

  it('recordSymbolAccess increments counts and dedupes within a batch', () => {
    const n = codeIndex.recordSymbolAccess(db, project, [
      { symbol_name: 'computeEmbedding', file_path: 'src/core/embedding.js', kind: 'function' },
      { symbol_name: 'computeEmbedding', file_path: 'src/core/embedding.js', kind: 'function' }, // duplicate
      { symbol_name: 'hybridSearch', file_path: 'src/core/search.js', kind: 'function' },
    ]);
    assert.equal(n, 2, 'duplicate within one batch counts once');
    const emb = db.prepare("SELECT access_count, last_accessed_at FROM code_symbols WHERE symbol_name = 'computeEmbedding'").get();
    assert.equal(emb.access_count, 1);
    assert.ok(emb.last_accessed_at);
  });

  it('getTaskScopedSymbols records access for injected symbols', () => {
    codeIndex.getTaskScopedSymbols(db, project, 'vector embedding', 2000, { graph: buildGraph() });
    const row = db.prepare("SELECT access_count FROM code_symbols WHERE symbol_name = 'computeEmbedding'").get();
    assert.ok(row.access_count >= 1, 'injected symbols must be marked as used');
  });

  it('prefers more-accessed symbols within a file (usage-weighted)', () => {
    db.prepare("UPDATE code_symbols SET access_count = 50, last_accessed_at = datetime('now') WHERE symbol_name = 'cosineSimilarity'").run();
    db.prepare("UPDATE code_symbols SET access_count = 2 WHERE symbol_name = 'computeEmbedding'").run();
    const { symbols } = codeIndex.getTaskScopedSymbols(db, project, 'embedding', 4000, { graph: buildGraph() });
    const file = symbols.filter(s => s.file_path === 'src/core/embedding.js');
    assert.ok(file.length >= 2);
    assert.equal(file[0].symbol_name, 'cosineSimilarity', 'higher access_count must sort first');
  });

  it('falls back to most-retrieved files when the task matches nothing', () => {
    // Mark search.js as heavily used; query matches no file
    db.prepare("UPDATE code_symbols SET access_count = 99 WHERE symbol_name = 'hybridSearch'").run();
    const { files } = codeIndex.getTaskScopedSymbols(db, project, 'zzz no match zzz', 4000, { graph: buildGraph() });
    assert.ok(files.includes('src/core/search.js'), 'usage-weighted fallback must pick the hot file');
  });

  it('getTopSymbols returns most-retrieved first', () => {
    // Two separate retrieval batches → startSession accumulates 2 uses
    codeIndex.recordSymbolAccess(db, project, [{ symbol_name: 'startSession', file_path: 'src/core/session.js', kind: 'function' }]);
    codeIndex.recordSymbolAccess(db, project, [
      { symbol_name: 'startSession', file_path: 'src/core/session.js', kind: 'function' },
      { symbol_name: 'hybridSearch', file_path: 'src/core/search.js', kind: 'function' },
    ]);
    const top = codeIndex.getTopSymbols(db, project, { limit: 5 });
    assert.equal(top[0].symbol_name, 'startSession');
    assert.equal(top[0].access_count, 2);
    assert.ok(top.every(t => t.access_count > 0));
  });

  it('symbolStats reports access totals', () => {
    codeIndex.recordSymbolAccess(db, project, [{ symbol_name: 'hybridSearch', file_path: 'src/core/search.js', kind: 'function' }]);
    const stats = codeIndex.symbolStats(db, project);
    assert.equal(stats.accesses, 1);
    assert.equal(stats.accessedSymbols, 1);
  });
});

// ─── XML rendering ──────────────────────────────────────────────────

describe('code-index XML rendering', () => {
  it('emits compact, escaped XML', () => {
    const xml = codeIndex.renderSymbolsXML([
      { file_path: 'src/a.ts', symbol_name: 'foo', kind: 'function', signature: 'foo<T>(x: "a&b")', doc: 'doc <tag>', body: '{ return 1; }' },
    ]);
    assert.ok(xml.includes('<code_symbols count="1">'));
    assert.ok(xml.includes('<symbol file="src/a.ts" name="foo" kind="function">'));
    assert.ok(!xml.includes('a&b<'), 'raw & must be escaped');
    assert.ok(xml.includes('a&amp;b'));
    assert.ok(xml.includes('doc &lt;tag&gt;'));
  });

  it('returns empty string for no symbols', () => {
    assert.equal(codeIndex.renderSymbolsXML([]), '');
  });
});

// ─── Distilled summaries ───────────────────────────────────────────

describe('code-index summaries', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-codeidx-sum-' + Date.now());
  beforeEach(() => { db = createTestDb(); codeIndex.ingestProject(db, project, { graph: buildGraph() }); });
  afterEach(() => { db.close(); });

  it('falls back to docstring/signature summary when LLM is unavailable', async () => {
    const r = await codeIndex.summarizeSymbols(db, project, { limit: 4 });
    assert.ok(r.summarized + r.fallback >= 4);
    const row = db.prepare("SELECT summary FROM code_symbols WHERE symbol_name = 'computeEmbedding'").get();
    assert.ok(row.summary && row.summary.length > 5, 'summary should be non-trivial');
    assert.ok(row.summary.includes('embedding') || row.summary.includes('text') || row.summary.includes('vector'));
  });

  it('does not re-summarize symbols that already have summaries', async () => {
    db.prepare("UPDATE code_symbols SET summary = 'x'").run();
    const r = await codeIndex.summarizeSymbols(db, project, { limit: 4 });
    assert.equal(r.summarized, 0);
    assert.equal(r.fallback, 0);
  });
});

// ─── Session compactor ─────────────────────────────────────────────

describe('session compactor', () => {
  let db;
  const project = path.join(os.tmpdir(), 'ac-compact-' + Date.now());
  beforeEach(() => { db = createTestDb(); });
  afterEach(() => { db.close(); });

  it('compacts a raw transcript with template fallback when no LLM', async () => {
    const entries = [];
    for (let i = 0; i < 50; i++) {
      entries.push({ role: 'user', content: 'step ' + i + ': refactor the auth module' });
      entries.push({ role: 'assistant', content: 'did step ' + i + ' with success' });
    }
    const r = await compactor.compactTranscript(entries, {});
    assert.ok(r.summary.length > 20);
    assert.ok(r.chunks >= 1);
    assert.ok(r.inputChars > 0);
    assert.ok(r.ratio > 0 && r.ratio < 0.5, 'should compress meaningfully');
  });

  it('compacts session observations and stores a history record', async () => {
    const insert = db.prepare(
      "INSERT INTO observations (session_id, project_path, type, title, content, tags) VALUES (?, ?, 'decision', ?, ?, '[]')"
    );
    for (let i = 0; i < 45; i++) {
      insert.run('sess-1', project, 'Decision ' + i, 'Chose approach ' + i + ' for the token budget engine');
    }
    const r = await compactor.compactObservations(db, { sessionId: 'sess-1', project });
    assert.equal(r.inputCount, 45);
    assert.equal(r.stored, true);
    assert.ok(r.summary.length > 20);
    const history = compactor.getCompactionHistory(db, { sessionId: 'sess-1' });
    assert.equal(history.length, 1);
    assert.equal(history[0].output, r.summary);
  });

  it('returns empty for a session with no observations', async () => {
    const r = await compactor.compactObservations(db, { sessionId: 'sess-empty', project });
    assert.equal(r.inputCount, 0);
    assert.equal(r.summary, '');
    assert.equal(r.stored, false);
  });
});

// ─── Diff ingestion (integration: real temp project + generator) ───

describe('code-index diff ingestion', () => {
  let db;
  let project;
  beforeEach(() => {
    db = createTestDb();
    project = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-diff-'));
  });
  afterEach(() => {
    db.close();
    fs.rmSync(project, { recursive: true, force: true });
  });

  it('re-indexes changed files via the deterministic generator', async () => {
    fs.mkdirSync(path.join(project, 'src'), { recursive: true });
    fs.writeFileSync(path.join(project, 'src', 'mod.js'), 'export function hello(name) {\n  return "hi " + name;\n}\n');
    fs.writeFileSync(path.join(project, 'src', 'other.js'), 'export const TWO = 2;\n');

    // Full ingest first
    const r1 = codeIndex.ingestProject(db, project, { regenerate: true });
    assert.equal(r1.status, 'ok');
    const before = db.prepare('SELECT COUNT(*) c FROM code_symbols WHERE project_path = ?').get(project).c;
    assert.ok(before >= 1);

    // Modify one file, then diff-ingest it
    fs.writeFileSync(path.join(project, 'src', 'mod.js'), 'export function hello(name, greet = "yo") {\n  return greet + " " + name;\n}\n');
    const r = await codeIndex.ingestDiff(db, project, { files: ['src/mod.js'] });
    assert.equal(r.status, 'ok');
    assert.deepEqual(r.changedFiles, ['src/mod.js']);
    assert.equal(r.memorySaved, true);
    const row = db.prepare("SELECT * FROM code_symbols WHERE project_path = ? AND symbol_name = 'hello'").get(project);
    assert.ok(row.body.includes('greet'), 'body should reflect the change');
    // A change memory observation was recorded
    const obs = db.prepare("SELECT COUNT(*) c FROM observations WHERE project_path = ? AND tags LIKE '%code-change%'").get(project).c;
    assert.equal(obs, 1);
  });
});
