#!/usr/bin/env node
/**
 * auto-setup.js — Postinstall auto-discovery for agentic-cortex.
 *
 * Runs automatically when agentic-cortex is installed as a dependency
 * (npm install agentic-cortex). Checks if knowledge.md exists in the
 * parent project and creates it if not, installs git hooks, and generates
 * the codebase graph. Zero user action needed.
 *
 * Triggered by: package.json "postinstall" script
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Shared discovery files module (also used by cli.js setup command)
const { createDiscoveryFiles } = require('./create-discovery-files');

// INIT_CWD is set by npm to the directory where npm install was run
// This is the PARENT project, not agentic-cortex's own directory
const projectDir = process.env.INIT_CWD || process.cwd();

// Only run auto-setup if we're being installed INTO another project
// (not when agentic-cortex installs its own dev dependencies)
const isDependencyInstall = projectDir !== path.resolve(__dirname, '..');
if (!isDependencyInstall) {
  // We're in agentic-cortex's own directory — skip
  process.exit(0);
}

const knowledgePath = path.join(projectDir, 'knowledge.md');
const templatePath = path.join(__dirname, '..', 'templates', 'knowledge.md');

// Skip if knowledge.md already exists (don't overwrite user's setup)
if (fs.existsSync(knowledgePath)) {
  console.error('[agentic-cortex] knowledge.md already exists at ' + knowledgePath + ' — skipping auto-setup');
  process.exit(0);
}

console.error('[agentic-cortex] Auto-setup triggered by postinstall in ' + projectDir);

try {
  // Step 1: Create knowledge.md from template
  if (fs.existsSync(templatePath)) {
    fs.copyFileSync(templatePath, knowledgePath);
    console.error('[agentic-cortex]   created knowledge.md');
  } else {
    // Minimal fallback
    const minimal = '# Agentic Cortex Memory Instructions\n\n## Persistent Memory\n\nUse `agentic-cortex save` to persist observations.\nAt session start, check below for injected context.\n\n<!-- MEMORY_CONTEXT_START -->\n<!-- MEMORY_CONTEXT_END -->\n';
    fs.writeFileSync(knowledgePath, minimal, 'utf-8');
    console.error('[agentic-cortex]   created minimal knowledge.md (template not found)');
  }

  // Step 2: Generate codebase graph
  const graphScript = path.join(__dirname, 'generate-graph.mjs');
  if (fs.existsSync(graphScript)) {
    try {
      execSync('node "' + graphScript + '" --output xml', {
        encoding: 'utf-8',
        timeout: 30000,
        cwd: projectDir,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      console.error('[agentic-cortex]   codebase graph generated');
    } catch (err) {
      console.error('[agentic-cortex]   graph generation skipped: ' + (err.message || '').split('\n')[0]);
    }
  }

  // Step 3: Inject context
  const injectScript = path.join(__dirname, 'inject-memory.mjs');
  if (fs.existsSync(injectScript)) {
    try {
      execSync('node "' + injectScript + '" "' + projectDir.replace(/\\/g, '/') + '"', {
        encoding: 'utf-8',
        timeout: 60000,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      console.error('[agentic-cortex]   context injected into knowledge.md');
    } catch (err) {
      if (err.stdout) process.stderr.write(err.stdout.toString());
      console.error('[agentic-cortex]   injection completed with warnings');
    }
  }

  // Step 4: Install git hooks
  const gitDir = path.join(projectDir, '.git');
  if (fs.existsSync(gitDir) && fs.statSync(gitDir).isDirectory()) {
    try {
      const hookDir = path.join(gitDir, 'hooks');
      if (!fs.existsSync(hookDir)) fs.mkdirSync(hookDir, { recursive: true });
      const hookContent = '#!/bin/sh\n# Auto-generated by agentic-cortex auto-setup\nagentic-cortex inject 2>/dev/null || true\n';
      const hookNames = ['post-merge', 'post-checkout', 'post-rewrite', 'post-commit'];
      let installed = 0;
      for (const hookName of hookNames) {
        const hookPath = path.join(hookDir, hookName);
        if (!fs.existsSync(hookPath)) {
          fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });
          installed++;
        }
      }
      if (installed > 0) {
        console.error('[agentic-cortex]   installed ' + installed + ' git hooks');
      }
    } catch (err) {
      console.error('[agentic-cortex]   git hooks skipped: ' + err.message);
    }
  }

  // Step 5: Create multi-agent discovery files
  const created = createDiscoveryFiles(projectDir);
  for (const f of created) {
    console.error('[agentic-cortex]   created ' + f);
  }

  console.error('[agentic-cortex] Auto-setup complete! Agent context is ready.');
  console.log(JSON.stringify({
    status: 'auto_setup_complete',
    project: projectDir,
    knowledgeMd: knowledgePath,
    message: 'agentic-cortex is now active in this project. Agents will discover it automatically.',
  }));

} catch (err) {
  // Auto-setup is best-effort — never break the parent install
  console.error('[agentic-cortex] Auto-setup failed (non-fatal): ' + err.message);
  process.exit(0);
}
